### ISSUE TITLE
Version of Qt5

### ISSUE THREAD

**Issue by yakomaxa** [viur-framework/pyodide-with-pyqt5#2]
Thank you for sharing an exciting project.  I'm trying to reproduce your work, and I have a question. My question is about the version of Qt5.

I found your make.sh script hardcodes the path of Qt5 as qt5, and I'm replacing it for my own. 
What exact version of Qt did you use to build this project? 
I'm using PyQt bundled in the repo, and I want to know the version of Qt compatible with this specific PyQt source.
I want to reproduce your setting as possible.

Bests.

**Comment by phneutral** [comment]
Hello yakomaxa, 
Thank you for your question. As you may have seen, the last commit in this repo was already in 2020. It was a test project that was not followed up. Therefore, we can no longer answer your question. 

I have taken your question as an opportunity to archive the repo. We should have done this earlier. 

Many greetings ph
